mysite/urls.py
from django.urls import path
from mysite import views
app_name="mysite"
urlpatterns = [
    path('contact/',views.contact,name="contact"),
    path('book/',views.book,name="book"),
    path('service/',views.allservice,name="service"),
    path('about/',views.about,name="about"),
    path('booking_detail/',views.booking_detail,name="booking_detail"),
]

orane/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('mysite/',include('mysite.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/models.py
from django.db import models
from django.contrib.auth.models import User

class services(models.Model):
    user = models.ForeignKey(User,on_delete= models.CASCADE)
    s_name = models.CharField(max_length=200)
    s_description=models.TextField()
    s_image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.s_name

class service(models.Model):
    name = models.ForeignKey(services,on_delete=models.CASCADE)
    sub_name = models.CharField(max_length=200,null=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True)
    price=models.DecimalField(decimal_places=2,max_digits=10)
    offered_price=models.DecimalField(decimal_places=2,max_digits=10)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sub_name

class booking(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250,blank=True)
    service = models.ForeignKey(services,on_delete=models.CASCADE)
    dateVisit = models.CharField(max_length=250,blank=True)
    timeVisit = models.CharField(max_length=250,blank=True)
    email = models.CharField(max_length=250,blank=True)
    contact = models.IntegerField(blank=True)
    notes = models.TextField(blank=True)
    booked_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name

class contactus(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250,blank=True)
    subject = models.CharField(max_length=250,blank=True)
    email = models.EmailField(blank=True)
    msz = models.TextField(blank=True)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name

mysite/views.py
from django.shortcuts import render
from mysite.models import services,service,booking,contactus
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect

all_services=services.objects.all().order_by('s_name')
lateset_service = services.objects.all().order_by('-id')[0]
def all_cats():
    #All Categories with sub categories
    main=[]
    for i in all_services:
        ab = []
        ab.append(i.s_name)
        ab += list(service.objects.filter(name=i).values())
        main.append(ab) 
    return main

def index(request):
    print(lateset_service.s_name)
    return render(request,'index.html',{'sr':all_services,'ls':lateset_service})

def contact(request):
    if request.method=="POST":
        fn = request.POST['fname']
        ln = request.POST['lname']
        em = request.POST['email']
        sub = request.POST['subject']
        msz = request.POST['message']

        data = contactus(first_name=fn,last_name=ln,email=em,subject=sub,msz=msz)
        data.save()
        return render(request,'contact.html',{'sr':all_services,'ls':lateset_service,'status':'Thanks for your feedback, we will contact you soon!!!'})

    return render(request,'contact.html',{'sr':all_services,'ls':lateset_service})

def book(request):
    if request.method == "POST":
        fn = request.POST['fname']
        ln = request.POST['lname']
        dt = request.POST['date']
        tm = request.POST['time']
        em = request.POST['email']
        con = request.POST['contact']
        srv = request.POST['treatment']
        note = request.POST['note']

        srv_obj = services.objects.get(id=srv)
        data = booking(first_name=fn,last_name=ln,service=srv_obj,dateVisit=dt,timeVisit=tm,email=em,contact=con,notes=note)
        data.save()
        # try:
        #     msz = 'Dear {} {} your service {} booked with service ID:{}\n See you on {} at {}'.format(fn,ln,srv_obj.s_name,data.id,dt,tm)
        #     mail = EmailMessage('Service Booking Summary', msz, to=[em,])
        #     mail.send()
        # except:
        #     rs = "Invalid email address or check your internet connection"
            # return render(request,'booking.html',{'sr':all_services,'ls':lateset_service,'result':rs})
        return HttpResponseRedirect('/mysite/booking_detail?id='+str(data.id))
    return render(request,'booking.html',{'sr':all_services,'ls':lateset_service})

def about(request):
    return render(request,'about.html',{'sr':all_services,'ls':lateset_service})

def allservice(request):
    all=all_cats()
    if 'id' in request.GET:
        id=request.GET['id']
        services = service.objects.filter(name__id=id)

        return render(request,'services.html',{'all':services,'srch':'1','sr':all_services,'ls':lateset_service})     
    return render(request,'services.html',{'all':all,'sr':all_services,'ls':lateset_service})

def booking_detail(request):
    if 'id' in request.GET:
        id = request.GET['id']
        booking_obj = booking.objects.get(id=id) 
    return render(request,'booking_details.html',{'book':booking_obj,'all':all,'sr':all_services,'ls':lateset_service})

templates/about.html
{% extends "base.html"%}
{% load staticfiles %}
{% block body %}
<div class="slide-one-item home-slider owl-carousel">
   
    <div class="site-blocks-cover inner-page-cover" style="background-image: url({% static 'images/hero_bg_2.jpg'%});" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">

          <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
            <h2 class="text-white font-weight-light mb-2 display-1">About Us</h2>
            <p class="text-white">We will give you the best branded products like L'oreal, Matrix, Charyal's, Lotus, Schawrzckof, Aroma etc.we have well experienced staff.</p>
          </div>
        </div>
      </div>
    </div>  

  </div>
<div class="site-section bg-light" id="about">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
          <h2 class="site-section-heading font-weight-light text-black text-center">Welcome To FashionIsta</h2>
        <p class="text-center">
          FashionIsta is one of the most trusted salons. Whether you’re looking for a completely new style or want to enhance your existing look, our talented team of professionals are here to make it happen. We provide expert advice tailored to your specific wants and needs.
<br><br>
Our friendly staff will make you feel like you’re at home. We use quality products and the latest styling techniques to bring out your very best. House of Hair Salon & Spa promises to provide you with 5-star service that will surpass your expectations.
<br><br>
Call and schedule an appointment at FashionIsta today and let us help you experience the incredible difference even a single visit to our salon can make.
        </p>
      </div>
    </div>
  </div>
</div>


  <div class="site-section bg-light" id="barber">
    <div class="container">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7">
          <h2 class="site-section-heading font-weight-light text-black text-center">Our Barbers</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="{% static 'images/person_1.jpg'%}" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Jean Smith</h2>
          <p class="mb-4">Providing a wide range of innovative and trendy beauty treatments to the inhabitants are the beauty salons from the area.</p>
          <p>
            <a href="https://twitter.com/hashtag/beautysalon?lang=en" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="https://www.instagram.com/explore/tags/beautysalon/?hl=en" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="https://www.facebook.com/Experts-Unisex-Saloon-518142321856535/" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="{% static 'images/person_2.jpg'%}" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">Claire Smith</h2>
          <p class="mb-4">Super Style Hair And Beauty Saloon in CMC offers guests a revitalizing experience through its contemporary amenities and impeccable services.</p>
          <p>
            <a href="https://twitter.com/hashtag/beautysalon?lang=en" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="https://www.instagram.com/explore/tags/beautysalon/?hl=en" class="pl-3 pr-3"><span class="icon-instagram"></span></a>  
            <a href="https://www.facebook.com/Experts-Unisex-Saloon-518142321856535/" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
        <div class="col-md-6 col-lg-4 text-center mb-5" data-aos="fade-up">
          <img src="{% static 'images/person_4.jpg'%}" alt="Image" class="img-fluid w-50 rounded-circle mb-4">
          <h2 class="text-black font-weight-light mb-4">John Smith</h2>
          <p class="mb-4">At this spa, the services are broadly categorised as body therapies and treatments, facial treatments, natural packs and scrubs.</p>
          <p>
            <a href="https://twitter.com/hashtag/beautysalon?lang=en" class="pl-0 pr-3"><span class="icon-twitter"></span></a>
            <a href="https://www.instagram.com/explore/tags/beautysalon/?hl=en" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
            <a href="https://www.facebook.com/Experts-Unisex-Saloon-518142321856535/" class="pl-3 pr-3"><span class="icon-facebook"></span></a>
          </p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="site-section border-top">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h2 class="mb-4 text-black">We want you look fabulous</h2>
          <p class="mb-0"><a href="{% url 'mysite:book'%}" class="btn btn-primary py-3 px-5 text-white">Visit Our Salon Now</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
{% load staticfiles%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FashionIsta &mdash;  First choice of fasion lovers</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,700,900|Display+Playfair:200,300,400,700"> 
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/mediaelementplayer.min.css">


    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.js'%}"></script>
  </head>
  <body>
  
  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    



    <header class="site-navbar py-1" role="banner">

      <div class="container-fluid">
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2" data-aos="fade-down">
            <h1 class="mb-0"><a href="{% url 'index'%}" class="text-black h2 mb-0">FashionInsta</a></h1>
          </div>
          <div class="col-10 col-md-8 d-none d-xl-block" data-aos="fade-down">
            <nav class="site-navigation position-relative text-right text-lg-center" role="navigation">

              <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block">
                <li class="">
                  <a href="{% url 'index'%}">Home</a>
                </li>
                <li class="has-children">
                  <a href="{% url 'mysite:service'%}">Services</a>
                  <ul class="dropdown">
                      {% for i in sr %}
                        <li><a href="{% url 'mysite:service'%}?id={{i.id}}">{{i.s_name}}</a></li>
                      {% endfor %}
                    
                  </ul>
                </li>
                <li><a href="{% url 'mysite:about'%}">About</a></li>
                <li><a href="{% url 'mysite:book'%}">Book Online</a></li>
                <li><a href="{% url 'mysite:contact'%}">Contact</a></li>
              </ul>
            </nav>
          </div>

          <div class="col-6 col-xl-2 text-right" data-aos="fade-down">
            <div class="d-none d-xl-inline-block">
              <ul class="site-menu js-clone-nav ml-auto list-unstyled d-flex text-right mb-0" data-class="social">
                <li>
                  <a href="https://facebook.com" class="pl-0 pr-3 text-black"><span class="icon-facebook"></span></a>
                </li>
                <li>
                  <a href="https://twitter.com" class="pl-3 pr-3 text-black"><span class="icon-twitter"></span></a>
                </li>
                <li>
                  <a href="https://instagram.com" class="pl-3 pr-3 text-black"><span class="icon-instagram"></span></a>
                </li>
                <li>
                  <a href="https://youtube.com" class="pl-3 pr-3 text-black"><span class="icon-youtube-play"></span></a>
                </li>
              </ul>
            </div>

            <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

          </div>

        </div>
      </div>
      
    </header>
    {% block body %}

    {% endblock %}
    <div class="site-section bg-light" id="latest">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
                <h2 class="display-1 text-black line-height-1 site-section-heading mb-4 pb-3">Latest Service</h2>
            </div>
            <div class="col-lg-6 mb-5">
              <img src="/media/{{ls.s_image}}" alt="Image" class="img-md-fluid" style="height:100%;width:100%;">
            </div>
            <div class="col-lg-6 bg-white p-md-5 align-self-center">
              <h5 class="display-4 text-black line-height-1 site-section-heading mb-4 pb-3"> <a href="{% url 'mysite:service'%}?id={{ls.id}}">{{ls.s_name}}</a></h5>
              <p class="text-black lead"><em>&ldquo;{{ls.s_description}}&rdquo;</em></p>
              <p class="lead text-black">&mdash; <em>{{ls.user.username}}</em></p>
            </div>
          </div>
        </div>
      </div>
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="mb-5">
              <h3 class="footer-heading mb-4">About FashionInsta</h3>
              <p>FashionInsta is one of the most trusted salons. Whether you’re looking for a completely new style or want to enhance your existing look, our talented team of professionals are here to make it happen. We provide expert advice tailored to your specific wants and needs.</p>
            </div>            
          </div>
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Quick Menu</h3>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="{% url 'index'%}">Home</a></li>
                  <li><a href="{% url 'mysite:about'%}#barber">Barbers</a></li>
                  <li><a href="/#latest">Latest Service</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="{% url 'mysite:about'%}">About Us</a></li>
                  <li><a href="{% url 'mysite:service'%}">All Services</a></li>
                  <li><a href="{% url 'mysite:contact'%}">Contact Us</a></li>
                </ul>
              </div>
            </div>

            

          </div>

          <div class="col-lg-4 mb-5 mb-lg-0">
           

            <div class="mb-5">
              <h3 class="footer-heading mb-2">Social Side</h3>
              <p>Our friendly staff will make you feel like you’re at home. We use quality products and the latest styling techniques to bring out your very best. House of Hair Salon & Spa promises to provide you with 5-star service that will surpass your expectations.</p>
              <div class="mb-5">
              <a href="https://www.facebook.com/Experts-Unisex-Saloon-518142321856535/" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
              <a href="https://twitter.com/hashtag/beautysalon?lang=en" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
              <a href="https://www.instagram.com/explore/tags/beautysalon/?hl=en" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
            </div>

            </div>

          </div>
          
        </div>
      </div>
    </footer>
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'js/jquery-ui.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'js/jquery.countdown.min.js'%}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js'%}"></script>
  <script src="{% static 'js/aos.js'%}"></script>

  <script src="{% static 'js/main.js'%}"></script>
    
  </body>
</html>

templates/booking.html
{% extends "base.html"%}
{% load staticfiles %}
{% block body %}
{% if result %}
  <script>
    alert("{{result}}");
  </script>
{% endif %}
    <div class="slide-one-item home-slider owl-carousel">
   
      <div class="site-blocks-cover inner-page-cover" style="background-image: url({% static 'images/hero_bg_2.jpg'%});" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center text-center">

            <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
              <h2 class="text-white font-weight-light mb-2 display-1">Online Booking</h2>

              
            </div>
          </div>
        </div>
      </div>  

    </div>



    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-7 mb-5">

            

            <form method="post" class="p-5 bg-white">
            {% csrf_token %}
              <h2 class="mb-4 site-section-heading">Book Now</h2>
              <p class="msz"></p>
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="fname">First Name</label>
                  <input type="text" id="fname" class="form-control" name="fname" placeholder="First Name">
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="lname">Last Name</label>
                  <input type="text" id="lname" class="form-control" name="lname" placeholder="Last Name">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="date">Date</label> 
                  <input type="text" id="date" name="date" class="form-control datepicker px-2" placeholder="Date of visit">
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="email">Time</label> 
                  <input type="time" id="time" name="time" class="form-control" placeholder="Time of Visit" required>
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-6 mb-3 mb-md-0">
                  <label class="text-black" for="email">Email</label> 
                  <input type="email" id="email" name="email" class="form-control px-2" placeholder="Email Address">
                </div>
                <div class="col-md-6">
                  <label class="text-black" for="email">Contact</label> 
                  <input type="number" name="contact" id="contact" class="form-control" placeholder="Contact Number">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="treatment">Service You Want</label> 
                  <select name="treatment" id="treatment" class="form-control">
                    {% for i in sr %}
                    <option value="{{i.id}}">{{i.s_name}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="text-black" for="note">Notes</label> 
                  <textarea name="note" id="note" cols="30" name="notes" rows="5" class="form-control" placeholder="Write your notes or questions here..."></textarea>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" id="book" value="Send" class="btn btn-primary py-2 px-4 text-white">
                </div>
              </div>
            </form>
          </div>
          <div class="col-md-5">
            
            <div class="p-4 mb-3 bg-white">
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">203  Mountain View, Industrial Area, Mohali, India</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">fashionista@fashion.com</a></p>

            </div>
            
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
               <p class="">FashionIsta is one of the most trusted salons. Whether you’re looking for a completely new style or want to enhance your existing look, our talented team of professionals are here to make it happen. We provide expert advice tailored to your specific wants and needs.</p> 
             <p class="">Call and schedule an appointment at FashionIsta today and let us help you experience the incredible difference even a single visit to our salon can make.
</p>
              <p><a href="{% url 'mysite:about'%}" class="btn btn-primary px-4 py-2 text-white">More Info</a></p>
            </div>

          </div>
        </div>
      </div>
    </div>
    <script>
    $(function(){
      $('#date').change(function(){
        let sd = new Date($(this).val());
        let cd = new Date();
        if(sd<cd){
        
          $('.msz').addClass('alert alert-danger').html("Invalid Date");
          $('#book').attr('disabled','disabled');
        }else{
          $('.msz').removeClass('alert alert-danger').html(" ");
          $('#book').removeAttr('disabled');
        }
      });
    });
  
    </script>
    
{% endblock %}

  

templates/index.html
{% extends "base.html"%}
{% load staticfiles %}
{% block body %}
<div class="slide-one-item home-slider owl-carousel">
      
  <div class="site-blocks-cover" style="background-image: url({% static 'images/hero_bg_1.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">

        <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
          <h5 class="text-white font-weight-light text-uppercase">Welcome to FashionInsta</h5>
          <h2 class="text-white font-weight-light mb-2 display-1">Salon Expert</h2>

          <p><a href="{% url 'mysite:book'%}" class="btn btn-black py-3 px-5">Book Now!</a></p>
        </div>
      </div>
    </div>
  </div>  

  <div class="site-blocks-cover" style="background-image: url({% static 'images/hero_bg_2.jpg' %});" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center text-center">

        <div class="col-md-8" data-aos="fade-up" data-aos-delay="400">
          <h2 class="text-white font-weight-light mb-2 display-1">Beautiful Hair, Healthy You!</h2>

          <p><a href="#" class="btn btn-black py-3 px-5">Book Now!</a></p>
        </div>
      </div>
    </div>
  </div>  

</div>


<div class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-lg-4 text-center">
        <h3 class="line-height-1 mb-3"><span class="d-block display-4 line-height-1 text-black">Welcome to</span> <span class="d-block display-4 line-height-1"><em class="text-primary font-weight-bold">Hair Salon</em></span></h3>
        <p>FashionInsta is one of the most trusted salons. Whether you’re looking for a completely new style or want to enhance your existing look, our talented team of professionals are here to make it happen. We provide expert advice tailored to your specific wants and needs.
        </p>
        <p><a href="{% url 'mysite:about'%}"><small class="text-uppercase font-weight-bold">Read More</small></a></p>
      </div>
      <div class="col-md-6 col-lg-4">
        <figure class="h-100 hover-bg-enlarge">
          <div class="bg-image h-100 bg-image-md-height" style="background-image: url('images/img_2.jpg');"></div>
        </figure>
      </div>
      <div class="col-md-6 col-lg-4">
        <div class="border p-4 d-flex align-items-center justify-content-center h-100">
          <div class="text-center">
            <h2 class="text-primary h2 mb-5">Opening Hours</h2>
            <p class="mb-4">
              <span class="d-block font-weight-bold">Mon – Fri </span>
              10:00 AM – 8:30 PM
            </p>

            <p class="mb-4">
              <span class="d-block font-weight-bold">Saturday</span>
              Closed
            </p>

            <p class="mb-4">
              <span class="d-block font-weight-bold">Sunday</span>
              10:00 AM – 8:30 PM
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <div class="col-md-7">
        <h2 class="site-section-heading font-weight-light text-black text-center">Featured Services</h2>
      </div>
    </div>

    <div class="row">
      {% for i in sr %}
      <div class="col-md-6 col-lg-4 text-center mb-5 mb-lg-5">
        <div class="h-100 p-4 p-lg-5 bg-light site-block-feature-7">
          <img src="../media/{{i.s_image}}" class="icon flaticon-razor display-3 text-primary mb-4 d-block" alt="{{i.s_name}}" height="200" width="100%">
          <!-- <span class="icon flaticon-razor display-3 text-primary mb-4 d-block"></span> -->
          <h3 class="text-black h4">{{i.s_name}}</h3>
          <p>{{i.s_description}}</p>
          <a href="{% url 'mysite:service'%}"><strong class="font-weight-bold text-primary">View Details</strong></a>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</div>




<div class="site-blocks-cover overlay inner-page-cover" style="background-image: url({% static 'images/hero_bg_2.jpg'%}); background-attachment: fixed;">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">

      <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
        <h2 class="text-white font-weight-light mb-5 display-3">Experience Our Outstanding Services</h2>
        <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-single-big d-inline-block popup-vimeo"><span class="icon-play"></span></a>
      </div>
    </div>
  </div>
</div>  
{% endblock %}